**NumPy**

NumPy was created in 2005 by Travis Oliphant.

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [ ]:
def Hel():
  print("Hello I Am th Function")

In [ ]:
Hel()

Hello I Am th Function


In [ ]:
pip install numpy

# **Basics NumPy Array**

1] Basic Array Creation

In [ ]:
import numpy as np

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2d array
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

2] Array Generation Function

In [ ]:
arr=np.arange(0,11,2)   #Array Range Use "arange()"
arr

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
za=np.zeros(6); #printing zeros vector
za

array([0., 0., 0., 0., 0., 0.])

In [ ]:
zar=np.zeros((6,6));  #printing zeros 2d array
zar

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
one=np.ones((6,6));  #printing zeros 2d array
one

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [ ]:
arr=np.linspace(1,10,3)   #printing element with liniear space (start,end,space between elements)
arr

array([ 1. ,  5.5, 10. ])

3] Random Generation Function

In [ ]:
np.random.rand(10) #it gives 5 random element

array([0.97823292, 0.26700391, 0.47975517, 0.77336311, 0.20760032,
       0.94230066, 0.79651591, 0.28749848, 0.38626105, 0.20139433])

Standardization: Transforms data to have mean = 0 and standard deviation = 1; values are often around -3 to +3, but not always.

Normalization: Scales data to a fixed range of 0 to 1.

In [ ]:
np.random.randn(10) # standardization

array([ 1.01168997, -1.32855504, -0.73672594,  1.29065547,  0.17770296,
       -0.1906816 ,  0.37309727, -0.33381015,  0.55033287, -1.34645679])

In [ ]:
np.random.randint(10,20,5) #generate 5 number between 10 to 20

array([18, 12, 15, 16, 16])

4] Array Attributes

In [ ]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.shape   # return rows and cols

(3, 3)

In [ ]:
arr.size     # return hhow many elements are present in array

9

In [ ]:
arr.dtype    # return data type of array

dtype('int64')

5] Array Methods

In [ ]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr.min()

np.int64(1)

In [ ]:
arr.max()

np.int64(9)

In [ ]:
arr.sum()

np.int64(45)

In [ ]:
np.sum(arr,0)  # col sum

array([12, 15, 18])

In [ ]:
np.sum(arr,1) # row sum

array([ 6, 15, 24])

In [ ]:
arr.mean()

np.float64(5.0)

In [ ]:
arr.std()

np.float64(2.581988897471611)

In [ ]:
arr.argmax()

np.int64(8)

In [ ]:
arr.argmin()

np.int64(0)

6] Reshaping and resizing

In [ ]:
arr=np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
arr.reshape(6,5)  # it convert array into 2d array : 6 rows and 5 colums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr.reshape(5,6)  # it convert array into 2d array : 5 rows and 6 colums

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

# **Arrays Indexing and Slicing**

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

1] NumPy Indexing and Slicing Of Vector

In [ ]:
arr[6] #accessing value using indexing

np.int64(17)

In [ ]:
arr[1:5] # slicing values start from 1 and end on 5

array([12, 13, 14, 15])

In [ ]:
arr[:5] # slicing values start from 0th index  and end on 5

array([11, 12, 13, 14, 15])

In [ ]:
arr[3:] # slicing values start from 3rd index  and end

array([14, 15, 16, 17, 18, 19, 20])

In [ ]:
arr[3::2] # slicing values start from 3rd index to end steps = 2

array([14, 16, 18, 20])

2] NumPy Indexing and Slicing Of Matrix

In [ ]:
arr=np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [ ]:
arr[0]

array([1, 2, 3, 4, 5])

In [ ]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[0,2] # 0th row and 2nd value

np.int64(3)

In [ ]:
arr[5,4]  # 5th row and 4th value = 30

np.int64(30)

In [ ]:
arr[3:6,3:5]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [ ]:
arr[0:2,1:3] # for col we go with 0th to 2nd index and for row we go from 1st to 3rd index

array([[2, 3],
       [7, 8]])

In [ ]:
slice = arr[1:5,1:4]
slice

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19],
       [22, 23, 24]])

In [ ]:
arr[:,3]  # it return 3rd column

array([ 4,  9, 14, 19, 24, 29])

In [ ]:
arr[2,:] # it return 2nd row

array([11, 12, 13, 14, 15])

3] Boolean Indexing

In [ ]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
arr=arr[bool_index]   # so basically in previous one we just check elements who are divide by 0 means even so it marks those all as true and in this we are only printing true values

arr

array([12, 14, 16, 18, 20])

# **Array Operations**

1] Arithmetic Operations

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([6,7,8,9,10])

In [ ]:
a1 + a2    # for size must be same of both the arrays

array([ 7,  9, 11, 13, 15])

In [ ]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [ ]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [ ]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [ ]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

2] Broadcasting

In [ ]:
l=[10,20,30,40]
l

[10, 20, 30, 40]

In [ ]:
#l +10  # it is not working so here is a concept called bradcasting
arr=np.array(l)

In [ ]:
arr + 10

array([20, 30, 40, 50])

3] Deep and shallow copy

In [ ]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
slice = a[0:5]
slice = slice * 10        # we are updating slice part   # and chnages are not affect main array so this is a deep copy
slice

array([10, 20, 30, 40, 50])

In [ ]:
a   # after that we are checking like those changes are heppen in a array so those are not affected by slice part
    # but if there is a list then changes are happen

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# Deep copy :- separate copy. No change on original data.

# Shallow copy :- changes made will be reflected in original data too.

4] Matrix Operations

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
B

array([[5, 6],
       [7, 8]])

In [ ]:
A * B # It is simple multiplication using index value

array([[ 5, 12],
       [21, 32]])

In [ ]:
A @ B  # This is the real one matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
np.dot(A,B)  # Same matrix multiplication

array([[19, 22],
       [43, 50]])

In [ ]:
A

array([[1, 2],
       [3, 4]])

In [ ]:
A.T    # This is transpose its like row, col = col, row

array([[1, 3],
       [2, 4]])

# **Advance Array Manipulation**

1] Stacking Array

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
b

array([5, 6, 7, 8])

In [ ]:
np.vstack((a,b))  # vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

2] Splitting Array

In [ ]:
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.hsplit(c,4) # horizontally spliting array in 4 parts # you need equal division at time of spliting

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [ ]:
np.vsplit(c,2)   # vertically spliting array in 2 parts  # you need equal division at time of spliting

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
a = np.vsplit(c,4)

In [ ]:
for i in a:
  print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
